runtime : nodejs16

# env_variables:
#     DB_HOST: 34.128.73.107,
#     DB_USERNAME: root,
#     DB_PASSWORD: root,
#     DB_NAME: eventapp

service : default

# handlers:
# - url: /.*
# script: auto

handlers:
  - url: /styles
    static_dir: public/styles

  - url: /images
    static_dir: public/images

  - url: /.*
    script: auto


